name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./desktop -> target"

      - name: Install SDL2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  build-linux:
    name: Build (Linux)
    needs: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./desktop -> target"

      - name: Install SDL2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Build release binary
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chip8-linux
          path: desktop/target/release/desktop
          retention-days: 7

  build-windows:
    name: Build (Windows)
    needs: lint
    runs-on: windows-2022

    defaults:
      run:
        working-directory: ./desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./desktop -> target"

      - name: Build release binary
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chip8-windows
          path: desktop/target/release/desktop.exe
          retention-days: 7
